import Link from "next/link";
import { ArrowUpRight, Check, ChevronRight, CircleDot, FolderKanban, Gauge, GitBranch, GitCommitHorizontal, Mail, MoreHorizontal, Plus, ShieldCheck, SlidersHorizontal, UserPlus, UsersRound } from "lucide-react";

import { collaborators, releases, teamMembers } from "@/components/tracebox/issue-data";
import { Avatar, MetricCard, SectionHeading, StatusPill, Surface } from "@/components/tracebox/primitives";
import { Button } from "@/components/ui/button";

export type WorkspaceSection = "teams" | "collaborators" | "releases";

const sectionCopy: Record<WorkspaceSection, { eyebrow: string; title: string; description: string }> = {
  teams: { eyebrow: "Workspace / people", title: "Teams", description: "Keep ownership clear across the work that moves through TraceBox." },
  collaborators: { eyebrow: "Workspace / access", title: "Collaborators", description: "Manage workspace access and see where outside contributors are active." },
  releases: { eyebrow: "Delivery / releases", title: "Releases", description: "Follow the trace from issue closure to a confident production release." },
};

function TeamsPage() {
  return <><div className="grid gap-3 sm:grid-cols-3"><MetricCard icon={UsersRound} label="Active members" value="12" detail="Across 3 teams" /><MetricCard icon={CircleDot} label="Owned issues" value="38" detail="6 need triage" /><MetricCard icon={GitBranch} label="Updates today" value="24" detail="Across 4 projects" /></div><div className="mt-3 grid gap-3 lg:grid-cols-[1.15fr_0.85fr]"><Surface><div className="flex items-center justify-between border-b border-border/80 px-4 py-3"><div><h2 className="text-sm font-semibold">Platform team</h2><p className="mt-0.5 text-xs text-muted-foreground">The team responsible for the command center.</p></div><Button size="sm" variant="outline" className="h-8 gap-1.5 text-xs"><UserPlus className="h-3.5 w-3.5" /> Add member</Button></div><div className="divide-y divide-border/60">{teamMembers.map((member) => <div key={member.name} className="flex items-center gap-3 px-4 py-3"><Avatar name={member.name} tone={member.tone} /><div className="min-w-0 flex-1"><p className="text-sm font-medium">{member.name}</p><p className="mt-0.5 text-xs text-muted-foreground">{member.role} · {member.activity}</p></div><span className="hidden rounded-full border border-emerald-500/25 bg-emerald-500/10 px-2 py-0.5 text-[10px] text-emerald-700 dark:text-emerald-300 sm:inline-flex">Active</span><Button variant="ghost" size="icon" className="h-8 w-8 text-muted-foreground" aria-label={`More actions for ${member.name}`}><MoreHorizontal className="h-4 w-4" /></Button></div>)}</div></Surface><Surface><div className="border-b border-border/80 px-4 py-3"><h2 className="text-sm font-semibold">Team signal</h2><p className="mt-0.5 text-xs text-muted-foreground">A light operational pulse, not a vanity metric.</p></div><div className="space-y-5 p-4"><div><div className="flex items-center justify-between text-xs"><span className="text-muted-foreground">Issue ownership</span><span className="font-mono">86%</span></div><div className="mt-2 h-2 rounded-full bg-muted"><div className="h-full w-[86%] rounded-full bg-primary" /></div></div><div><div className="flex items-center justify-between text-xs"><span className="text-muted-foreground">Review coverage</span><span className="font-mono">74%</span></div><div className="mt-2 h-2 rounded-full bg-muted"><div className="h-full w-[74%] rounded-full bg-violet-500" /></div></div><div className="border-t border-border/70 pt-4 text-xs leading-5 text-muted-foreground">Two members are at capacity this week. Consider moving the two urgent issues in the Web queue.</div><Link href="/dashboard/issues" className="flex items-center gap-1 text-xs font-medium text-primary hover:underline">Open issue queue <ArrowUpRight className="h-3 w-3" /></Link></div></Surface></div></>;
}

function CollaboratorsPage() {
  return <><div className="grid gap-3 sm:grid-cols-3"><MetricCard icon={UsersRound} label="Collaborators" value="24" detail="18 active this month" /><MetricCard icon={Mail} label="Pending invites" value="02" detail="Awaiting a response" /><MetricCard icon={ShieldCheck} label="Access reviews" value="100%" detail="No stale accounts" /></div><Surface className="mt-3"><div className="flex flex-col gap-3 border-b border-border/80 p-3 sm:flex-row sm:items-center sm:justify-between"><div className="flex items-center gap-2"><Button variant="outline" size="sm" className="h-8 gap-1.5 text-xs"><SlidersHorizontal className="h-3.5 w-3.5" /> All access</Button><span className="font-mono text-[10px] text-muted-foreground">24 collaborators</span></div><Button size="sm" className="h-8 gap-1.5 text-xs"><Plus className="h-3.5 w-3.5" /> Invite collaborator</Button></div><div className="hidden grid-cols-[minmax(220px,1fr)_110px_140px_100px_32px] gap-3 border-b border-border/70 bg-muted/35 px-4 py-2 font-mono text-[10px] uppercase tracking-[0.12em] text-muted-foreground sm:grid"><span>Person</span><span>Role</span><span>Access</span><span>Last seen</span><span /></div><div className="divide-y divide-border/60">{collaborators.map((person) => <div key={person.email} className="grid gap-2 px-4 py-3 sm:grid-cols-[minmax(220px,1fr)_110px_140px_100px_32px] sm:items-center sm:gap-3"><div className="flex min-w-0 items-center gap-3"><Avatar name={person.name} tone={person.tone} size="sm" /><div className="min-w-0"><p className="truncate text-sm font-medium">{person.name}</p><p className="truncate text-xs text-muted-foreground">{person.email}</p></div></div><span className="text-xs text-muted-foreground sm:text-foreground">{person.role}</span><span className="text-xs text-muted-foreground">{person.access}</span><span className="font-mono text-[11px] text-muted-foreground">{person.lastSeen}</span><Button variant="ghost" size="icon" className="hidden h-8 w-8 text-muted-foreground sm:inline-flex" aria-label={`More actions for ${person.name}`}><MoreHorizontal className="h-4 w-4" /></Button></div>)}</div></Surface></>;
}

function ReleasesPage() {
  return <><div className="grid gap-3 sm:grid-cols-3"><MetricCard icon={Gauge} label="Active releases" value="02" detail="One ships this week" /><MetricCard icon={ShieldCheck} label="Release health" value="92%" detail="Across active milestones" trend="+8%" /><MetricCard icon={GitCommitHorizontal} label="Commits traced" value="184" detail="Since the last release" /></div><div className="mt-3 grid gap-3 lg:grid-cols-[1.2fr_0.8fr]"><Surface><div className="flex items-center justify-between border-b border-border/80 px-4 py-3"><div><h2 className="text-sm font-semibold">Release train</h2><p className="mt-0.5 text-xs text-muted-foreground">Milestones with the signal your team can act on.</p></div><Button size="sm" className="h-8 gap-1.5 text-xs"><Plus className="h-3.5 w-3.5" /> New release</Button></div><div className="divide-y divide-border/60">{releases.map((release) => <div key={release.name} className="px-4 py-4"><div className="flex flex-col gap-2 sm:flex-row sm:items-start sm:justify-between"><div><p className="text-sm font-medium">{release.name}</p><p className="mt-1 font-mono text-[11px] text-muted-foreground">Target {release.due} · {release.status}</p></div><span className={release.risk === "Low" || release.risk === "None" ? "text-xs text-emerald-600 dark:text-emerald-300" : "text-xs text-amber-600 dark:text-amber-300"}>{release.risk} risk</span></div><div className="mt-3 flex items-center gap-3"><div className="h-2 flex-1 rounded-full bg-muted"><div className={release.risk === "Medium" ? "h-full rounded-full bg-amber-500" : "h-full rounded-full bg-primary"} style={{ width: `${release.progress}%` }} /></div><span className="w-9 text-right font-mono text-[11px]">{release.progress}%</span></div></div>)}</div></Surface><Surface><div className="border-b border-border/80 px-4 py-3"><h2 className="text-sm font-semibold">Release checklist</h2><p className="mt-0.5 text-xs text-muted-foreground">Operational confidence before shipping.</p></div><div className="space-y-3 p-4 text-sm"><div className="flex items-center gap-2"><span className="flex h-5 w-5 items-center justify-center rounded-full bg-emerald-500/15 text-emerald-600 dark:text-emerald-300"><Check className="h-3 w-3" /></span>Critical issues resolved</div><div className="flex items-center gap-2"><span className="flex h-5 w-5 items-center justify-center rounded-full bg-emerald-500/15 text-emerald-600 dark:text-emerald-300"><Check className="h-3 w-3" /></span>Review coverage above 80%</div><div className="flex items-center gap-2"><span className="flex h-5 w-5 items-center justify-center rounded-full bg-amber-500/15 text-amber-600 dark:text-amber-300">2</span>At-risk issues assigned</div><Link href="/dashboard/issues" className="mt-3 flex items-center gap-1 text-xs font-medium text-primary hover:underline">Review open issues <ArrowUpRight className="h-3 w-3" /></Link></div></Surface></div></>;
}

export function WorkspaceSectionPage({ section }: { section: WorkspaceSection }) {
  const copy = sectionCopy[section];
  const content = section === "teams" ? <TeamsPage /> : section === "collaborators" ? <CollaboratorsPage /> : <ReleasesPage />;
  return <main className="mx-auto max-w-[1500px] p-4 sm:p-6 lg:p-8"><SectionHeading eyebrow={copy.eyebrow} title={copy.title} description={copy.description} /><div className="mt-6">{content}</div></main>;
}
