import { z } from "zod";
const uuid = z.string().uuid();
const date = z.string().regex(/^\d{4}-\d{2}-\d{2}$/).nullable().default(null);
export const searchParseSchema = z.object({
  statuses: z.array(uuid).max(1).default([]), resolutions: z.array(z.enum(["FIXED","DUPLICATE","WONT_FIX","INVALID","CANNOT_REPRODUCE","WORKS_AS_EXPECTED"])).max(1).default([]), priorities: z.array(z.enum(["P0","P1","P2","P3","P4"])).max(1).default([]), severities: z.array(z.enum(["BLOCKER","CRITICAL","MAJOR","MINOR","TRIVIAL"])).max(1).default([]), types: z.array(z.enum(["BUG","ENHANCEMENT","TASK","SECURITY","PERFORMANCE","REGRESSION"])).max(1).default([]),
  assignee: z.union([uuid, z.literal("ME")]).nullable().default(null), reporter: z.union([uuid, z.literal("ME")]).nullable().default(null), component_id: uuid.nullable().default(null), affected_version_id: uuid.nullable().default(null), target_milestone_id: uuid.nullable().default(null), labels: z.array(uuid).max(1).default([]), text: z.string().max(200).nullable().default(null),
  status_categories: z.array(z.enum(["TRIAGE","OPEN","IN_PROGRESS","REVIEW","RESOLVED","CLOSED"])).max(6).default([]), visibility: z.enum(["PROJECT","RESTRICTED"]).nullable().default(null), created_from: date, created_to: date, updated_from: date, updated_to: date, custom_field_id: uuid.nullable().default(null), custom_value: z.string().max(200).nullable().default(null), unresolved: z.boolean().default(false), overdue: z.boolean().default(false), critical: z.boolean().default(false),
}).strict();
export type SearchParseResult = z.infer<typeof searchParseSchema>;
const nullableString = { type: ["string", "null"] } as const;
export const SEARCH_JSON_SCHEMA = { type: "object", additionalProperties: false, required: ["statuses","resolutions","priorities","severities","types","assignee","reporter","component_id","affected_version_id","target_milestone_id","labels","text","status_categories","visibility","created_from","created_to","updated_from","updated_to","custom_field_id","custom_value","unresolved","overdue","critical"], properties: {
  statuses: { type: "array", maxItems: 1, items: { type: "string" } }, resolutions: { type: "array", maxItems: 1, items: { type: "string" } }, priorities: { type: "array", maxItems: 1, items: { type: "string" } }, severities: { type: "array", maxItems: 1, items: { type: "string" } }, types: { type: "array", maxItems: 1, items: { type: "string" } }, assignee: nullableString, reporter: nullableString, component_id: nullableString, affected_version_id: nullableString, target_milestone_id: nullableString, labels: { type: "array", maxItems: 1, items: { type: "string" } }, text: nullableString, status_categories: { type: "array", maxItems: 6, items: { type: "string" } }, visibility: nullableString, created_from: nullableString, created_to: nullableString, updated_from: nullableString, updated_to: nullableString, custom_field_id: nullableString, custom_value: nullableString, unresolved: { type: "boolean" }, overdue: { type: "boolean" }, critical: { type: "boolean" },
} } as const;
