export type IssueLinkEdge = { id: string; source_issue_id: string; target_issue_id: string; relationship: string };
export type BlastRadiusNode = { id: string; issueNumber?: number; keyLabel?: string; title?: string; componentName?: string | null; milestoneId?: string | null; severity?: string | null; priority?: string | null; depth: number };
export type BlastRadiusResult = { nodes: BlastRadiusNode[]; edges: Array<{ from: string; to: string; relationship: string }>; directBlocked: number; transitiveBlocked: number; affectedComponents: number; affectedMilestones: number; criticalIssues: number };
export function getBlastRadius(rootId: string, links: IssueLinkEdge[], meta: Map<string, Omit<BlastRadiusNode, "id" | "depth">>, visibleIds: Set<string>, maxDepth = 5, maxNodes = 200): BlastRadiusResult {
  const adjacency = new Map<string, Array<{ to: string; relationship: string }>>();
  for (const link of links) { let from: string | undefined; let to: string | undefined; if (link.relationship === "BLOCKS") [from, to] = [link.source_issue_id, link.target_issue_id]; else if (link.relationship === "DEPENDS_ON") [from, to] = [link.target_issue_id, link.source_issue_id]; if (from && to && visibleIds.has(from) && visibleIds.has(to)) (adjacency.get(from) ?? (adjacency.set(from, []), adjacency.get(from)!)).push({ to, relationship: link.relationship }); }
  const root = visibleIds.has(rootId) ? rootId : ""; const seen = new Set(root ? [root] : []); const queue = root ? [{ id: root, depth: 0 }] : []; const nodes: BlastRadiusNode[] = root ? [{ id: root, depth: 0, ...meta.get(root) }] : []; const edges: BlastRadiusResult["edges"] = []; let directBlocked = 0;
  while (queue.length && seen.size < maxNodes) { const current = queue.shift()!; if (current.depth >= maxDepth) continue; for (const next of adjacency.get(current.id) ?? []) { if (seen.has(next.to)) continue; seen.add(next.to); edges.push({ from: current.id, to: next.to, relationship: next.relationship }); if (current.depth === 0) directBlocked++; nodes.push({ id: next.to, depth: current.depth + 1, ...meta.get(next.to) }); queue.push({ id: next.to, depth: current.depth + 1 }); if (seen.size >= maxNodes) break; } }
  const components = new Set(nodes.map((n) => n.componentName).filter(Boolean)); const milestones = new Set(nodes.map((n) => n.milestoneId).filter(Boolean)); const critical = nodes.filter((n) => n.id !== root && (n.severity === "BLOCKER" || n.severity === "CRITICAL" || n.priority === "P0")).length;
  return { nodes, edges, directBlocked, transitiveBlocked: Math.max(0, seen.size - 1), affectedComponents: components.size, affectedMilestones: milestones.size, criticalIssues: critical };
}
