import { calculateReportQuality, type IssueForQuality } from "./report-quality";
export type TriageIssueInput = IssueForQuality & { id: string; issue_number: number; project_id: string; title: string; type: string; priority: string; severity: string; status_id: string; component_id: string | null; affected_version_id: string | null; target_milestone_id: string | null; visibility?: string | null; updated_at?: string | null };
export type ComponentOption = { id: string; name: string; default_assignee_id?: string | null };
export type AssigneeOption = { user_id: string; display_name?: string | null };
export type DuplicateCandidateInput = { id: string; issue_number: number; project_key?: string; title: string; description?: string | null; type?: string; priority?: string; severity?: string; status?: string | null; similarity?: number };
const clip = (value: string | null | undefined, max: number) => value ? value.slice(0, max) : null;
/** AI receives bounded, redacted defect evidence. Comments, file bodies, and integration payloads never cross the provider boundary. */
export function buildTriageContext(input: { issue: TriageIssueInput; components: ComponentOption[]; assignees: AssigneeOption[]; duplicateCandidates: DuplicateCandidateInput[]; attachments?: never; projectKey?: string }) {
  const q = calculateReportQuality(input.issue);
  return { issue: { id: input.issue.id, issue_number: input.issue.issue_number, key: input.projectKey ? `${input.projectKey}-${input.issue.issue_number}` : null, title: clip(input.issue.title, 200), description: clip(input.issue.description, 4000), steps_to_reproduce: clip(input.issue.steps_to_reproduce, 3000), expected_behavior: clip(input.issue.expected_behavior, 1500), actual_behavior: clip(input.issue.actual_behavior, 1500), environment: clip(input.issue.environment, 1000), type: input.issue.type, priority: input.issue.priority, severity: input.issue.severity, status_id: input.issue.status_id, component_id: input.issue.component_id, affected_version_id: input.issue.affected_version_id, target_milestone_id: input.issue.target_milestone_id, report_quality: { score: q.score, present: q.present, missing: q.missing }, updated_at: input.issue.updated_at ?? null }, reportQuality: q, components: input.components.slice(0, 100).map((c) => ({ id: c.id, name: clip(c.name, 100), default_assignee_id: c.default_assignee_id ?? null })), possibleAssignees: input.assignees.slice(0, 100).map((a) => ({ user_id: a.user_id, display_name: clip(a.display_name, 100) })), candidateDuplicates: input.duplicateCandidates.slice(0, 3).map((c) => ({ id: c.id, issue_number: c.issue_number, key: c.project_key ? `${c.project_key}-${c.issue_number}` : null, title: clip(c.title, 120), description: clip(c.description, 1500), type: c.type ?? null, priority: c.priority ?? null, severity: c.severity ?? null, status: c.status ?? null, similarity: c.similarity ?? null })) };
}
export type TriageContext = ReturnType<typeof buildTriageContext>;
